-- * JDBC 계정 생성
CREATE USER C##JDBC IDENTIFIED BY JDBC;
--   권한 부여 : CONNECT, RESOURCE
GRANT CONNECT, RESOURCE TO C##JDBC;
--   테이블 스페이스 설정
ALTER USER C##JDBC DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

--------- JDBC 계정 접속 후 아래 실행 -----------
DROP TABLE MEMBER;
DROP SEQUENCE SEQ_MEMBER_ID;

CREATE TABLE MEMBER (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    AGE NUMBER
);

CREATE SEQUENCE SEQ_MEMBER_ID
START WITH 1
INCREMENT BY 1
NOCACHE;