-- * MUSIC 계정 생성
CREATE USER C##MUSIC IDENTIFIED BY MUSIC;
--   권한 부여 : CONNECT, RESOURCE
GRANT CONNECT, RESOURCE TO C##MUSIC;
--   테이블 스페이스 설정
ALTER USER C##MUSIC DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

--------- MUSIC 계정 접속 후 아래 실행 -----------
DROP TABLE MUSIC;
DROP SEQUENCE SEQ_MUSIC_ID;

CREATE TABLE MUSIC (
    ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(300) NOT NULL,
    SINGER VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_MUSIC_ID
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 데이터 조회 : SELECT
SELECT * FROM MUSIC;

-- 데이터 추가 : INSERT
INSERT INTO MUSIC VALUES (SEQ_MUSIC_ID.NEXTVAL, 'TAKE COVER', 'MR.BIG');
INSERT INTO MUSIC VALUES (SEQ_MUSIC_ID.NEXTVAL, 'BAD RAIN', 'SLASH');
INSERT INTO MUSIC VALUES (SEQ_MUSIC_ID.NEXTVAL, 'WELCOME TO THE JUNGLE', 'RHCP');

commit;